[package]
name = "MyMoveProject"
version = "0.1.0"
authors = ["YourName"]

[dependencies]
asgiref = "3.7.2"
asttokens = "2.4.1"
attrs = "23.2.0"
autobahn = "23.6.2"
Automat = "22.10.0"
cachetools = "5.3.3"
certifi = "2024.2.2"
cffi = "1.16.0"
channels = "3.0.4"
charset_normalizer = "3.3.2"
colorama = "0.4.6"
comm = "0.2.2"
constantly = "23.10.4"
cryptography = "42.0.5"
daphne = "3.0.2"
debugpy = "1.8.1"
decorator = "5.1.1"
defusedxml = "0.8.0-rc2"
dj_database_url = "2.1.0"
Django = "5.0.3"
django_allauth = "0.63.2"
django_crispy_forms = "2.1"
django_debug_toolbar = "4.3.0"
django_environ = "0.11.2"
djangorestframework = "3.15.1"
environ = "1.0"
exceptiongroup = "1.2.1"
executing = "2.0.1"
google_auth = "2.29.0"
gunicorn = "22.0.0"
hyperlink = "21.0.0"
idna = "3.6"
incremental = "22.10.0"
ipykernel = "6.29.4"
ipython = "8.24.0"
jedi = "0.19.1"
jupyter_client = "8.6.1"
jupyter_core = "5.7.2"
matplotlib_inline = "0.1.7"
mpmath = "1.3.0"
mysqlclient = "2.2.4"
nest_asyncio = "1.6.0"
numpy = "1.26.4"
oauthlib = "3.2.2"
packaging = "24.0"
parso = "0.8.4"
pillow = "10.2.0"
platformdirs = "4.2.2"
prompt_toolkit = "3.0.43"
psutil = "5.9.8"
psycopg2 = "2.9.9"
psycopg2_binary = "2.9.9"
pure_eval = "0.2.2"
pyasn1 = "0.5.1"
pyasn1_modules = "0.3.0"
pycparser = "2.21"
Pygments = "2.18.0"
PyJWT = "2.8.0"
pyOpenSSL = "24.1.0"
python_dateutil = "2.9.0.post0"
python_environ = "0.4.54"
python3_openid = "3.2.0"
pywin32 = { version = "303", optional = true, platforms = ["windows"] }
pyzmq = "26.0.3"
requests = "2.31.0"
requests_oauthlib = "2.0.0"
rsa = "4.9"
service_identity = "24.1.0"
six = "1.16.0"
social_auth_app_django = "5.4.0"
social_auth_core = "4.5.3"
sqlparse = "0.4.4"
stack_data = "0.6.3"
stripe = "8.9.0"
sympy = "1.12"
tornado = "6.4"
traitlets = "5.14.3"
Twisted = "24.3.0"
twisted_iocpsupport = { version = "1.0.4", optional = true, platforms = ["windows"] }
txaio = "23.1.1"
typing_extensions = "4.10.0"
tzdata = "2024.1"
urllib3 = "2.2.1"
wcwidth = "0.2.13"
whitenoise = "6.6.0"
zope_interface = "6.2"
